/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.taller;

/**
 *
 * @author rybel
 */
public class Plan extends javax.swing.JFrame {

    /**
     * Creates new form Plan
     */
    public Plan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePlan = new javax.swing.JTable();
        ButtonRegistrarPlan = new javax.swing.JButton();
        ButtonActualizarPlan = new javax.swing.JButton();
        ButtonEditarPlan = new javax.swing.JButton();
        ButtonEliminarPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 81, 81));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Planes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        TablePlan.setBackground(new java.awt.Color(204, 204, 204));
        TablePlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Costo"
            }
        ));
        jScrollPane1.setViewportView(TablePlan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 440, 310));

        ButtonRegistrarPlan.setBackground(new java.awt.Color(204, 204, 204));
        ButtonRegistrarPlan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonRegistrarPlan.setForeground(new java.awt.Color(0, 0, 0));
        ButtonRegistrarPlan.setText("Registrar Plan");
        jPanel1.add(ButtonRegistrarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 140, 30));

        ButtonActualizarPlan.setBackground(new java.awt.Color(204, 204, 204));
        ButtonActualizarPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonActualizarPlan.setForeground(new java.awt.Color(0, 0, 0));
        ButtonActualizarPlan.setText("Actualizar");
        jPanel1.add(ButtonActualizarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 110, 30));

        ButtonEditarPlan.setBackground(new java.awt.Color(204, 204, 204));
        ButtonEditarPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonEditarPlan.setForeground(new java.awt.Color(0, 0, 0));
        ButtonEditarPlan.setText("Editar");
        jPanel1.add(ButtonEditarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 110, 30));

        ButtonEliminarPlan.setBackground(new java.awt.Color(204, 204, 204));
        ButtonEliminarPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonEliminarPlan.setForeground(new java.awt.Color(0, 0, 0));
        ButtonEliminarPlan.setText("Eliminar");
        jPanel1.add(ButtonEliminarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizarPlan;
    private javax.swing.JButton ButtonEditarPlan;
    private javax.swing.JButton ButtonEliminarPlan;
    private javax.swing.JButton ButtonRegistrarPlan;
    private javax.swing.JTable TablePlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
