/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.taller;

/**
 *
 * @author rybel
 */
public class RegistrarPlan extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPlan
     */
    public RegistrarPlan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxDiaDesde = new javax.swing.JComboBox<>();
        ComboBoxMesDesde = new javax.swing.JComboBox<>();
        ComboBoxDiaHasta = new javax.swing.JComboBox<>();
        ComboBoxMesHasta = new javax.swing.JComboBox<>();
        ButtonAceptar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 81, 81));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Plan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        textNombre.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desde:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hasta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        ComboBoxDiaDesde.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxDiaDesde.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ComboBoxDiaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, 30));

        ComboBoxMesDesde.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxMesDesde.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ComboBoxMesDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, 30));

        ComboBoxDiaHasta.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxDiaHasta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ComboBoxDiaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 70, 30));

        ComboBoxMesHasta.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxMesHasta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ComboBoxMesHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 70, 30));

        ButtonAceptar.setBackground(new java.awt.Color(204, 204, 204));
        ButtonAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAceptar.setText("Aceptar");
        jPanel1.add(ButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, 30));

        ButtonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        ButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonCancelar.setText("Cancelar");
        jPanel1.add(ButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JComboBox<String> ComboBoxDiaDesde;
    private javax.swing.JComboBox<String> ComboBoxDiaHasta;
    private javax.swing.JComboBox<String> ComboBoxMesDesde;
    private javax.swing.JComboBox<String> ComboBoxMesHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
